version: "3"
services:
  prometheus:
    image: prom/prometheus:v2.4.3
    container_name: 'prometheus'
    volumes:
    - ./config/:/etc/prometheus/
    ports:
     - '9090:9090'
  grafana:
    image: grafana/grafana:5.2.4
    container_name: 'grafana'
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini  #grafana报警邮件配置
      - ./grafana/provisioning/:/etc/grafana/provisioning/  #配置grafana的prometheus数据源
    env_file:
      - ./grafana/config.monitoring  #grafana登录配置
    depends_on:
      - prometheus  #grafana需要在prometheus之后启动
  elasticsearch:
    image: elasticsearch:6.4.0
    container_name: elasticsearch
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小，稍微配置大点，不然有可能启动不成功
    volumes:
      - /usr/local/var/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - /usr/local/var/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana:6.4.0
    container_name: kibana
    links:  #同一个compose文件管理的服务可以直接用服务名访问，如果要给服务取别名则可以用links实现，如下面的es就是elasticsearch服务的别名
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
    ports:
      - 5601:5601

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.5.4
    container_name: filebeat
    privileged: true
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /usr/local/var/log/redis.log:/usr/local/var/log/redis.log
#      - /data/web/app/runtime/logs/buyer:/data/web/app/runtime/logs/buyer
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
  redis_exporter:
    image: oliver006/redis_exporter
    container_name: redis_exporter
    environment:
      - "REDIS_ADDR=redis://127.0.0.1:6379"
      - "REDIS_PASSWORD="
    ports:
      - 9121:9121
  mysqld_exporter:
    image: prom/mysqld-exporter
    container_name: mysqld-exporter
    environment:
      - "DATA_SOURCE_NAME=root:886887@(10.180.134.117:3306)/final"
    ports:
      - 9104:9104
