global:
  scrape_interval:     15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          application: prometheus

  - job_name: openapi
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.180.134.117:8082']
        labels:
          application: localhost