global:
  scrape_interval:     15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          application: prometheus

  - job_name: openapi
    scrape_interval: 1s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['127.0.0.1:8082']
        labels:
          application: localhost
  - job_name: "mysql"
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:9104']
        labels:
          instance: "mysql"
  - job_name: redis
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:9121']
        labels:
          instance: redis