filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/local/var/log/redis.log
    multiline:
      pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      negate: true
      match: after
      max_lines: 1000
      timeout: 3s
output.elasticsearch:
  hosts: ["127.0.0.1:9200"]
  index: "log-%{+yyyy.MM}"
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml
  # Set to true to enable config reloading
  reload.enabled: false
  # Period on which files under path should be checked for changes
  #reload.period: 10s