global:
  scrape_interval:     15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          application: prometheus

  - job_name: openapi
    scrape_interval: 1s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.3.9:8082']
        labels:
          application: localhost
  - job_name: 'mysql'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['mysql_exporter_master:9104']
        labels:
          instance: mysql
          application: mysql_exporter_master
      - targets: [ 'mysql_exporter_slave:9105' ]
          labels:
            instance: mysql
            application: mysql_exporter_slave
      - targets: [ 'mysql_exporter_master-1:9106' ]
          labels:
            instance: mysql
            application: mysql_exporter_master-1
      - targets: [ 'mysql_exporter_slave-1:9107' ]
          labels:
            instance: mysql
            application: mysql_exporter_slave-1
  - job_name: 'redis'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.3.9:9121']
        labels:
          instance: redis
          application: redis
